
services:
    nwserver:
        hostname: nwserver
        container_name: nwserver
        image: ${NWSERVER_IMAGE:-nwnxee/unified}:${NWSERVER_TAG:-build8193.36.12}
        env_file: ./config/nwserver.env
        restart: unless-stopped
        stdin_open: true
        tty: true
        volumes:
            - ./logs:/nwn/run/logs.0
            - ./:/nwn/home
            - ./logs:/nwn/data/bin/linux-x86/logs.0
        ports:
#            - '5122:5122/udp'
            - "${NWN_PORT:-5121}:${NWN_PORT:-5121}/udp"
